#!/bin/bash
# MCP Server Metrics Collector — v2 (adds components inventory)
# Deploy to each monitored host, run every 5 min via cron:
# */5 * * * * MONITOR_TOKEN=mcp-monitor-2026 /usr/local/bin/mcp-collector.sh
#
# v2 adds the `components` field — auto-detected per-host inventory of
# installed git repos (HEAD/branch/dirty count), supervisor/systemd
# services, and version strings (python/django/freeswitch/nginx). Used
# by the bbl-monitor /servers drift dashboard.

ENDPOINT="http://crawl.rgs.mx:8765/monitor/ingest"
MONITOR_TOKEN="${MONITOR_TOKEN:-REPLACE_ME}"

HOSTNAME_VAL=$(hostname -f 2>/dev/null || hostname)

# CPU count
CPU_COUNT=$(nproc 2>/dev/null || grep -c ^processor /proc/cpuinfo 2>/dev/null || echo 1)

# Load averages
read LOAD1 LOAD5 LOAD15 _ < /proc/loadavg

# Memory (MB)
MEM_LINE=$(free -m 2>/dev/null | awk '/^Mem:/{print $2,$3,$7}')
MEM_TOTAL=$(echo $MEM_LINE | awk '{print $1}')
MEM_USED=$(echo $MEM_LINE | awk '{print $2}')
MEM_FREE=$(echo $MEM_LINE | awk '{print $3}')
if [ -z "$MEM_TOTAL" ] || [ "$MEM_TOTAL" -eq 0 ] 2>/dev/null; then MEM_PCT="0"; else
  MEM_PCT=$(awk "BEGIN {printf \"%.1f\", ($MEM_USED/$MEM_TOTAL)*100}")
fi

# Primary network interface
NET_IFACE=$(ip route 2>/dev/null | awk '/^default/{print $5; exit}')
[ -z "$NET_IFACE" ] && NET_IFACE=$(ls /sys/class/net/ 2>/dev/null | grep -v lo | head -1)
[ -z "$NET_IFACE" ] && NET_IFACE="eth0"

NET_RX=0; NET_TX=0
if [ -f /proc/net/dev ]; then
  NET_LINE=$(awk -v iface="$NET_IFACE:" '$1==iface{print $2,$10}' /proc/net/dev)
  NET_RX=$(echo $NET_LINE | awk '{print $1}')
  NET_TX=$(echo $NET_LINE | awk '{print $2}')
  [ -z "$NET_RX" ] && NET_RX=0
  [ -z "$NET_TX" ] && NET_TX=0
fi

# Disk usage — build JSON array, skip tmpfs/devtmpfs/udev/loop
DISKS_JSON=$(df -BM 2>/dev/null | tail -n +2 | grep -v -E '^(tmpfs|devtmpfs|udev|/dev/loop)' | awk '
{
  gsub(/M/, "", $2); gsub(/M/, "", $3)
  pct = ($2 > 0) ? int($3/$2*100) : 0
  printf "{\"mount\":\"%s\",\"total_mb\":%s,\"used_mb\":%s,\"pct\":%d},", $6, $2, $3, pct
}' | sed 's/,$//')
DISKS_JSON="[$DISKS_JSON]"


# Calls in progress (FreeSwitch only — fs_cli must be available)
CALLS_IN_PROGRESS="null"
FS_CLI=$(command -v fs_cli 2>/dev/null || echo /usr/local/freeswitch-1.10.5.-release/bin/fs_cli)
if [ -x "$FS_CLI" ]; then
  _count=$($FS_CLI -x "show calls" 2>/dev/null | grep -E "^[0-9]+ total" | grep -oE "^[0-9]+")
  [ -n "$_count" ] && CALLS_IN_PROGRESS=$_count
fi

# ── Components inventory (auto-detected by path/binary presence) ─────────
# Three sub-maps:
#   git_repos: working copies under known paths (HEAD short SHA, branch,
#              uncommitted file count after filtering noise, last-commit subject)
#   services:  supervisor + systemd units that exist (RUNNING/STOPPED/active)
#   versions:  binary version strings (python/freeswitch/nginx/django)
# All best-effort: missing tools / missing paths just don't show up.
# Output shape: COMPONENTS_JSON = {"git_repos": [...], "services": [...], "versions": {...}}

# Git repos
GIT_REPOS_JSON=""
GIT_PATHS=(
    "/projects/bbl-django:bbl-django"
    "/opt/bbl-esl:bbl-esl"
    "/opt/bbl-monitor:bbl-monitor"
    "/opt/bbl-fs/bbl-fs-build:bbl-fs-build"
    "/opt/bbl-fs/bbl-fs-config:bbl-fs-config"
    "/opt/bbl-fs/bbl-ch-build:bbl-ch-build"
    "/home/gstreet/bbl-mcp:bbl-mcp"
)
for spec in "${GIT_PATHS[@]}"; do
    path="${spec%:*}"
    name="${spec#*:}"
    [ -d "$path/.git" ] || continue
    # safe.directory shim — postgres/freeswitch user dirs may have ownership
    # that would otherwise trip git's dubious-ownership refusal.
    head=$(git -C "$path" -c safe.directory="$path" rev-parse --short HEAD 2>/dev/null)
    branch=$(git -C "$path" -c safe.directory="$path" branch --show-current 2>/dev/null)
    # "Real drift" count: modified tracked files only, excluding common
    # per-host regenerated paths. Untracked files (^??) are usually
    # runtime artifacts (logs, DB caches, etc.) — NOT drift. staticfiles/
    # is regenerated by Django's collectstatic on each host. .bak/.tmp/
    # __pycache__ are workshop debris.
    uncommitted=$(git -C "$path" -c safe.directory="$path" status --porcelain 2>/dev/null \
        | grep -v '^??' \
        | grep -v -E 'staticfiles/|\.bak|__pycache__|\.pyc|\.tmp' \
        | wc -l)
    subject=$(git -C "$path" -c safe.directory="$path" log -1 --format=%s 2>/dev/null \
        | head -c 60 | sed 's/[\\"]/\\&/g')
    behind=0
    if [ -n "$branch" ]; then
        behind=$(git -C "$path" -c safe.directory="$path" rev-list --count "HEAD..origin/$branch" 2>/dev/null)
        [ -z "$behind" ] && behind=0
    fi
    obj="{\"name\":\"$name\",\"path\":\"$path\",\"head\":\"$head\",\"branch\":\"$branch\",\"uncommitted\":$uncommitted,\"behind\":$behind,\"subject\":\"$subject\"}"
    GIT_REPOS_JSON="${GIT_REPOS_JSON}${obj},"
done
GIT_REPOS_JSON="[${GIT_REPOS_JSON%,}]"

# Services (supervisor + systemd)
SERVICES_JSON=""
# supervisor units
if command -v supervisorctl >/dev/null 2>&1; then
    while IFS= read -r line; do
        sv_name=$(echo "$line" | awk '{print $1}')
        sv_status=$(echo "$line" | awk '{print $2}')
        [ -z "$sv_name" ] && continue
        # Filter to BBL-relevant supervisor units
        case "$sv_name" in
            bbl|celery:*|bbl-esl-outbound|bbl-esl-relay)
                obj="{\"name\":\"$sv_name\",\"type\":\"supervisor\",\"status\":\"$sv_status\"}"
                SERVICES_JSON="${SERVICES_JSON}${obj},"
                ;;
        esac
    done < <(supervisorctl status 2>/dev/null)
fi
# systemd units (only check ones we care about)
KNOWN_SYSTEMD=(bbl-monitor bbl-mcp freeswitch nginx postgresql redis-server)
for sv_name in "${KNOWN_SYSTEMD[@]}"; do
    if systemctl list-unit-files --no-pager 2>/dev/null | grep -q "^${sv_name}\.service"; then
        sv_status=$(systemctl is-active "$sv_name" 2>/dev/null)
        obj="{\"name\":\"$sv_name\",\"type\":\"systemd\",\"status\":\"$sv_status\"}"
        SERVICES_JSON="${SERVICES_JSON}${obj},"
    fi
done
SERVICES_JSON="[${SERVICES_JSON%,}]"

# Versions
VERS_PARTS=""
PY_VER=$(python3 --version 2>&1 | awk '{print $2}')
[ -n "$PY_VER" ] && VERS_PARTS="${VERS_PARTS}\"python\":\"$PY_VER\","

if [ -x "$FS_CLI" ]; then
    FS_VER=$($FS_CLI -x "version" 2>/dev/null | grep -oE "[0-9]+\.[0-9]+\.[0-9]+" | head -1)
    [ -n "$FS_VER" ] && VERS_PARTS="${VERS_PARTS}\"freeswitch\":\"$FS_VER\","
fi

if command -v nginx >/dev/null 2>&1; then
    NGX_VER=$(nginx -v 2>&1 | grep -oE "[0-9]+\.[0-9]+\.[0-9]+" | head -1)
    [ -n "$NGX_VER" ] && VERS_PARTS="${VERS_PARTS}\"nginx\":\"$NGX_VER\","
fi

# Django (only if a CH-style bbl-django checkout exists)
if [ -d /projects/bbl-django ] && [ -x /projects/bbl_env_py3/bin/python ]; then
    DJ_VER=$(/projects/bbl_env_py3/bin/python -c "import django; print(django.__version__)" 2>/dev/null)
    [ -n "$DJ_VER" ] && VERS_PARTS="${VERS_PARTS}\"django\":\"$DJ_VER\","
fi

VERSIONS_JSON="{${VERS_PARTS%,}}"

COMPONENTS_JSON="{\"git_repos\":$GIT_REPOS_JSON,\"services\":$SERVICES_JSON,\"versions\":$VERSIONS_JSON}"

PAYLOAD=$(cat <<JSONEOF
{
  "hostname": "$HOSTNAME_VAL",
  "cpu_count": $CPU_COUNT,
  "load_1m": $LOAD1,
  "load_5m": $LOAD5,
  "load_15m": $LOAD15,
  "mem_total_mb": ${MEM_TOTAL:-0},
  "mem_used_mb": ${MEM_USED:-0},
  "mem_free_mb": ${MEM_FREE:-0},
  "mem_pct": ${MEM_PCT:-0},
  "net_iface": "$NET_IFACE",
  "net_rx_bytes": $NET_RX,
  "net_tx_bytes": $NET_TX,
  "disks": $DISKS_JSON,
  "calls_in_progress": $CALLS_IN_PROGRESS,
  "components": $COMPONENTS_JSON
}
JSONEOF
)

curl -s -X POST "$ENDPOINT" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $MONITOR_TOKEN" \
  -d "$PAYLOAD" \
  --max-time 10 \
  > /dev/null 2>&1
