#!/bin/bash
# 04-cert.sh — Let's Encrypt certificates for FreeSWITCH WSS + SIP-TLS.
#
# Uses acme.sh (lighter than certbot, no nginx dependency, --standalone
# mode). On renewal, concatenates key+fullchain into wss.pem the way
# mod_sofia wants and reloads the client profile.
set -euo pipefail

# shellcheck disable=SC1091
. "$BBL_HOST_CONF"
CRT_DOMAIN="$BBL_DOMAIN"
CRT_EMAIL="${BBL_CERT_EMAIL:-admin@$BBL_DOMAIN}"

if [[ ! -d /etc/acme ]]; then
    echo "==> Installing acme.sh"
    apt-get install -y -q socat
    git clone --quiet https://github.com/acmesh-official/acme.sh.git /usr/src/acme
    /usr/src/acme/acme.sh --install --home /etc/acme --accountemail "$CRT_EMAIL" >/dev/null
fi

# Reload hook: assemble wss.pem from the renewed material, reload sofia
cat > /etc/acme/freeswitch-wss.sh <<EOF
#!/bin/bash
# Auto-generated by bbl-fs-build/04-cert.sh — DO NOT EDIT BY HAND
set -euo pipefail
cat /etc/acme/${CRT_DOMAIN}_ecc/${CRT_DOMAIN}.key /etc/acme/${CRT_DOMAIN}_ecc/fullchain.cer \
    > /etc/freeswitch/tls/wss.pem
chown freeswitch:freeswitch /etc/freeswitch/tls/wss.pem
chmod 640 /etc/freeswitch/tls/wss.pem
fs_cli -x 'sofia profile client restart reloadxml'
EOF
chmod 755 /etc/acme/freeswitch-wss.sh

# Source acme env so our PATH includes its tooling
# shellcheck disable=SC1091
. /etc/acme/acme.sh.env

echo "==> Issuing cert for $CRT_DOMAIN (acme.sh --standalone, port 80 must be reachable)"
mkdir -p /etc/freeswitch/tls
chown freeswitch:freeswitch /etc/freeswitch/tls

# --keylength ec-256 → ECDSA (smaller, faster, modern). Falls back to
# rsa if your hosting provider's network has issues; uncomment one only.
/etc/acme/acme.sh --issue \
    --accountemail "$CRT_EMAIL" \
    --standalone \
    --keylength ec-256 \
    -d "$CRT_DOMAIN" \
    || { echo "$0: cert issuance failed — see /etc/acme/acme.sh.log" >&2; exit 1; }

# Install + register the renewal hook so wss.pem stays in sync
/etc/acme/acme.sh --install-cert \
    --domain "$CRT_DOMAIN" \
    --ecc \
    --cert-file /etc/freeswitch/tls/${CRT_DOMAIN}.cert.pem \
    --key-file  /etc/freeswitch/tls/${CRT_DOMAIN}.key.pem \
    --fullchain-file /etc/freeswitch/tls/${CRT_DOMAIN}.fullchain.pem \
    --reloadcmd /etc/acme/freeswitch-wss.sh

echo "==> 04-cert.sh complete (acme.sh's own cron renews automatically)"
